export const enum RoutesPath {
  MAIN = '/',
  ABOUT = '/about',
  PRODUCTS = '/products',
  MICROCREDIT = '/products/microcredit',
  AUTOCREDIT = '/products/autocredit',
  ISLAMFINANCE = '/products/islam-finance',
  BUSINESSCREDIT = '/products/business-credit',
  BANKCREDIT = '/products/bank-credit',
  DATAUNLOAD = '/products/data-unload',
  FDATA = '/products/f-data',
  P2P = '/products/p2p',
  BNPL = '/products/bnpl',
  REVIEWS = '/reviews',
  WORK = '/work',
}
